//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Healthcare_sql
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccessList
    {
        public int AccessListPk_Id { get; set; }
        public int OptionID { get; set; }
        public string Value { get; set; }
        public System.DateTime ValidFrom { get; set; }
        public System.DateTime ValidTo { get; set; }
        public int Resolution { get; set; }
        public int AccessTierId { get; set; }
    
        public virtual AccessEntity AccessEntity { get; set; }
        public virtual AccessResolution AccessResolution { get; set; }
        public virtual AccessTier AccessTier { get; set; }
    }
}
