//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Healthcare_sql
{
    using System;
    using System.Collections.Generic;
    
    public partial class App
    {
        public int app_id { get; set; }
        public string Patient_name { get; set; }
        public string Phone { get; set; }
        public string Email_ID { get; set; }
        public string Department { get; set; }
        public string Doctor { get; set; }
        public Nullable<System.DateTime> App_Date { get; set; }
        public string Time_Slot { get; set; }
    }
}
