//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Healthcare_sql
{
    using System;
    using System.Collections.Generic;
    
    public partial class App_doc
    {
        public int Aph_id { get; set; }
        public string City_name { get; set; }
        public string Doctor_name { get; set; }
        public Nullable<System.DateTime> App_date { get; set; }
        public string TimeSlot { get; set; }
        public Nullable<System.DateTime> updateddate { get; set; }
        public string User_name { get; set; }
        public string txtotherdoc { get; set; }
        public string status { get; set; }
    }
}
