//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Healthcare_sql
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankWorkingHour
    {
        public string ban_id { get; set; }
        public string Working_Type { get; set; }
        public string Working_Time { get; set; }
        public string Day_Name { get; set; }
        public string Updated_By { get; set; }
        public Nullable<System.DateTime> Updated_Datetime { get; set; }
        public string others { get; set; }
    }
}
