//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Healthcare_sql
{
    using System;
    using System.Collections.Generic;
    
    public partial class bankinfo
    {
        public string ban_id { get; set; }
        public string bank_name { get; set; }
        public string bank_type { get; set; }
        public string owner_name { get; set; }
        public string address { get; set; }
        public string city { get; set; }
        public string zone { get; set; }
        public Nullable<decimal> pincode { get; set; }
        public string std1 { get; set; }
        public string phone1 { get; set; }
        public string std2 { get; set; }
        public string phone2 { get; set; }
        public string website { get; set; }
        public string email { get; set; }
        public Nullable<bool> organ_bank { get; set; }
        public Nullable<bool> blood_bank { get; set; }
        public Nullable<bool> eye_bank { get; set; }
        public Nullable<bool> organ_bone { get; set; }
        public Nullable<bool> organ_kidney { get; set; }
        public Nullable<bool> organ_heart { get; set; }
        public Nullable<bool> organ_pancreas { get; set; }
        public Nullable<bool> organ_skin { get; set; }
        public Nullable<bool> organ_liver { get; set; }
        public Nullable<bool> organ_umblical { get; set; }
        public Nullable<bool> blood_whole { get; set; }
        public Nullable<bool> blood_packed { get; set; }
        public Nullable<bool> blood_platelets { get; set; }
        public Nullable<bool> blood_plasma { get; set; }
        public Nullable<bool> blood_cryoprecipitate { get; set; }
        public Nullable<bool> blood_freshfrozenplasma { get; set; }
        public Nullable<bool> eye { get; set; }
        public Nullable<bool> application_fee { get; set; }
        public Nullable<bool> application_card { get; set; }
        public Nullable<bool> application_form { get; set; }
        public string application_others { get; set; }
        public string time_retrieval { get; set; }
        public Nullable<bool> organ_others { get; set; }
        public string organ_text { get; set; }
        public Nullable<bool> blood_factors { get; set; }
        public Nullable<bool> blood_others { get; set; }
        public string blood_factors_text { get; set; }
        public string blood_others_text { get; set; }
        public string fax { get; set; }
        public string updated_by { get; set; }
        public Nullable<System.DateTime> updated_datetime { get; set; }
        public Nullable<decimal> category_code { get; set; }
        public Nullable<int> Bank_Count { get; set; }
        public string approval { get; set; }
        public string vcUserName { get; set; }
        public string vcRoleType { get; set; }
    }
}
