//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Healthcare_sql
{
    using System;
    using System.Collections.Generic;
    
    public partial class BasicHealthDetail
    {
        public string user_id { get; set; }
        public string vcAge { get; set; }
        public string gender { get; set; }
        public string height_feet { get; set; }
        public string height_inch { get; set; }
        public string measure1 { get; set; }
        public string measure2 { get; set; }
        public string weight { get; set; }
        public string relationship_status { get; set; }
        public string blood_type { get; set; }
        public string BP_Systolic { get; set; }
        public string BP_Diastolic { get; set; }
        public string Cholesterol { get; set; }
        public System.DateTime Reinsertedon { get; set; }
    }
}
