//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Healthcare_sql
{
    using System;
    using System.Collections.Generic;
    
    public partial class BLOG_T
    {
        public int BL_ID { get; set; }
        public string BLOG_TITLE { get; set; }
        public string BLOG_LINK { get; set; }
    }
}
