//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Healthcare_sql
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookAppointment
    {
        public string vcName { get; set; }
        public string vcContactNo { get; set; }
        public string vcEmailID { get; set; }
        public Nullable<System.DateTime> dttmBookOn { get; set; }
        public string vcOrderID { get; set; }
        public string dttm_preferdDate { get; set; }
        public string vcPreferdTime { get; set; }
        public string vcDiseaseDesc { get; set; }
        public string vcBookOpFor { get; set; }
        public string vcEmailTextSent { get; set; }
        public Nullable<System.DateTime> dttm_UpdateOn { get; set; }
        public string vcUNameUpdateBy { get; set; }
        public string hospitalname { get; set; }
        public string Updatee { get; set; }
        public string docname { get; set; }
        public string vcusername { get; set; }
        public string providername { get; set; }
        public string chkorderid { get; set; }
        public Nullable<bool> flag { get; set; }
        public Nullable<int> app_type { get; set; }
        public string cardtype { get; set; }
        public string region { get; set; }
        public Nullable<System.DateTime> dtfollowdate { get; set; }
        public string age { get; set; }
        public Nullable<bool> AppointmentType { get; set; }
        public string vcqueryid { get; set; }
        public string referdoc { get; set; }
        public int Id { get; set; }
    }
}
