//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Healthcare_sql
{
    using System;
    using System.Collections.Generic;
    
    public partial class bot_table
    {
        public int id { get; set; }
        public string name { get; set; }
        public string Email { get; set; }
        public string Cell_Number { get; set; }
        public string query { get; set; }
    }
}
