//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Healthcare_sql
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClinicalResearchDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ClinicalResearchDetail()
        {
            this.ClinicalDoctors = new HashSet<ClinicalDoctor>();
        }
    
        public string id { get; set; }
        public string discipline { get; set; }
        public string Disease_Condition { get; set; }
        public string Study_Title { get; set; }
        public string Phase_of_Trial { get; set; }
        public string Status_of_Trial { get; set; }
        public Nullable<System.DateTime> Start_of_Trial { get; set; }
        public Nullable<double> Duration_of_trial { get; set; }
        public Nullable<System.DateTime> closing_trial_date { get; set; }
        public string Primary_Sponsor { get; set; }
        public string Secondry_Sponsor { get; set; }
        public string Monetory_Sponsor { get; set; }
        public string Sponsor_address { get; set; }
        public string sponsor_city { get; set; }
        public string contact_name1 { get; set; }
        public string contact_phone1 { get; set; }
        public string contact_email1 { get; set; }
        public string contact_name2 { get; set; }
        public string contact_phone2 { get; set; }
        public string contact_email2 { get; set; }
        public string Mcontact_name { get; set; }
        public string Mcontact_PHONE { get; set; }
        public string Mcontact_Email { get; set; }
        public string updated_by { get; set; }
        public Nullable<System.DateTime> updated_datetime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClinicalDoctor> ClinicalDoctors { get; set; }
    }
}
