//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Healthcare_sql
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cme_description
    {
        public int intCme_id { get; set; }
        public string vcCme_title { get; set; }
        public string vcCme_Responser { get; set; }
        public string vcCme_summary { get; set; }
        public string vcCmeReponserurl { get; set; }
        public string vcResponserImageType { get; set; }
        public string vcResponserImageName { get; set; }
        public byte[] imgResponserImage { get; set; }
        public string FilePath { get; set; }
        public string FileName { get; set; }
        public string vc_spec { get; set; }
        public string endorsement { get; set; }
        public string Index_content { get; set; }
    }
}
