//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Healthcare_sql
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConnectTransactions_api
    {
        public int ConnectTransactionPK_Id { get; set; }
        public int ReferralConnectPK_Id { get; set; }
        public string ProviderFrom { get; set; }
        public string ProviderTo { get; set; }
        public byte ProviderFromType { get; set; }
        public byte ProviderToType { get; set; }
        public short NewStatusID { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public string Comments { get; set; }
        public Nullable<short> SeenStatus { get; set; }
    
        public virtual ReferralConnect_api ReferralConnect_api { get; set; }
        public virtual ReferralEntityMaster ReferralEntityMaster { get; set; }
        public virtual ReferralEntityMaster ReferralEntityMaster1 { get; set; }
        public virtual ReferralStatusMaster ReferralStatusMaster { get; set; }
        public virtual ReferralStatusMaster ReferralStatusMaster1 { get; set; }
    }
}
