//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Healthcare_sql
{
    using System;
    using System.Collections.Generic;
    
    public partial class copyHospitalProcedure
    {
        public string hos_id { get; set; }
        public string specialization_name { get; set; }
        public string procedure_name { get; set; }
        public string other { get; set; }
        public string updated_by { get; set; }
        public Nullable<System.DateTime> updated_datetime { get; set; }
        public Nullable<int> Proc_cat { get; set; }
        public string Price_cat { get; set; }
        public string Price { get; set; }
        public int intHpId { get; set; }
    }
}
