//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Healthcare_sql
{
    using System;
    using System.Collections.Generic;
    
    public partial class Corporate
    {
        public int ID { get; set; }
        public string name { get; set; }
        public string Designation { get; set; }
        public string Cell { get; set; }
        public string Company { get; set; }
        public string City { get; set; }
        public string nemployees { get; set; }
    }
}
