//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Healthcare_sql
{
    using System;
    using System.Collections.Generic;
    
    public partial class CorporateDetail
    {
        public string corp_id { get; set; }
        public string corp_name { get; set; }
        public string corp_category { get; set; }
        public string corp_type { get; set; }
        public string owner_name { get; set; }
        public string address { get; set; }
        public string area_zone { get; set; }
        public string city { get; set; }
        public string country { get; set; }
        public Nullable<decimal> pincode { get; set; }
        public string primary_std { get; set; }
        public string primary_phone { get; set; }
        public string secondary_std { get; set; }
        public string secondary_phone { get; set; }
        public string fax_no { get; set; }
        public string email { get; set; }
        public string web_url { get; set; }
        public string other_info { get; set; }
        public string updated_by { get; set; }
        public Nullable<System.DateTime> updated_Datetime { get; set; }
        public string approval { get; set; }
        public string Ind_Name { get; set; }
        public string Ind_Mobile { get; set; }
        public string Ind_Email { get; set; }
        public string vcUsername { get; set; }
        public string vcRoleType { get; set; }
        public string vcAltEmail { get; set; }
    }
}
