//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Healthcare_sql
{
    using System;
    using System.Collections.Generic;
    
    public partial class Coupons4Pat
    {
        public int id { get; set; }
        public string Email { get; set; }
        public string City { get; set; }
        public string Hospital { get; set; }
        public Nullable<System.DateTime> CurrDate { get; set; }
        public string Docname { get; set; }
    }
}
