//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Healthcare_sql
{
    using System;
    using System.Collections.Generic;
    
    public partial class dept_hosrating
    {
        public string Hreview_id { get; set; }
        public string hos_id { get; set; }
        public Nullable<decimal> firstrating_value { get; set; }
        public Nullable<decimal> secondrating_value { get; set; }
        public Nullable<decimal> thirdrating_vlaue { get; set; }
        public Nullable<decimal> fourthrating_value { get; set; }
        public Nullable<decimal> fivthrating_value { get; set; }
        public Nullable<decimal> totalrating_value { get; set; }
        public Nullable<decimal> specialization_id { get; set; }
    }
}
