//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Healthcare_sql
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetailAccessCount
    {
        public long ID { get; set; }
        public string vcOrderID { get; set; }
        public Nullable<System.DateTime> dttmAccess { get; set; }
        public Nullable<int> iAccessCount { get; set; }
        public string vcAccessDetailFor { get; set; }
        public string vcUserName { get; set; }
    }
}
