//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Healthcare_sql
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiagnosticCentresContactDetail
    {
        public string dia_id { get; set; }
        public decimal Contact_ID { get; set; }
        public string Contact_Person { get; set; }
        public string designation { get; set; }
        public string std_code { get; set; }
        public string phone_no { get; set; }
        public string address { get; set; }
        public string email { get; set; }
        public string city { get; set; }
        public string area { get; set; }
        public Nullable<decimal> pincode { get; set; }
        public string remarks { get; set; }
        public string Updated_By { get; set; }
        public Nullable<System.DateTime> Updated_DateTime { get; set; }
    }
}
