//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Healthcare_sql
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiagnosticCentresDetail
    {
        public string dia_id { get; set; }
        public string dia_name { get; set; }
        public string address { get; set; }
        public string std1 { get; set; }
        public string phone1 { get; set; }
        public string std2 { get; set; }
        public string phone2 { get; set; }
        public string city { get; set; }
        public string zone { get; set; }
        public Nullable<decimal> pincode { get; set; }
        public string fax_no { get; set; }
        public string email { get; set; }
        public string website { get; set; }
        public Nullable<bool> open_all_days { get; set; }
        public Nullable<bool> open_24_hours { get; set; }
        public Nullable<bool> emergency_testing { get; set; }
        public string emergency_service_name { get; set; }
        public string accreditation_by { get; set; }
        public string discount { get; set; }
        public string branches { get; set; }
        public string tiesUp_with_specialized_lab { get; set; }
        public Nullable<bool> online_booking { get; set; }
        public string Online_Detail { get; set; }
        public string mobile_USG_Xray { get; set; }
        public string updated_by { get; set; }
        public Nullable<System.DateTime> updated_datetime { get; set; }
        public string closed_on { get; set; }
        public string Working_Hours { get; set; }
        public Nullable<bool> Clinical_Trails { get; set; }
        public string Clinical_Trails_Services { get; set; }
        public string other_info { get; set; }
        public Nullable<decimal> category_code { get; set; }
        public string folder_name { get; set; }
        public string contact_person { get; set; }
        public string approval { get; set; }
        public string vcUserName { get; set; }
        public string vcRoleType { get; set; }
        public Nullable<int> Count_DiaId { get; set; }
        public string Ind_Name { get; set; }
        public string Ind_Mobile { get; set; }
        public string Ind_Email { get; set; }
        public string vcAltEmail { get; set; }
        public string IntEmailId { get; set; }
        public string NatEmailId { get; set; }
        public string vcParentType { get; set; }
        public string vcChildDiag { get; set; }
        public string Source { get; set; }
        public string Country { get; set; }
    }
}
