//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Healthcare_sql
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiagnosticCentreService
    {
        public string Dia_ID { get; set; }
        public string Service_Name { get; set; }
        public string SubService_Name { get; set; }
        public string Rate { get; set; }
        public string Updated_By { get; set; }
        public Nullable<System.DateTime> Updated_DateTime { get; set; }
        public string other { get; set; }
        public string Test_Name { get; set; }
        public string Rate1 { get; set; }
    }
}
