//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Healthcare_sql
{
    using System;
    using System.Collections.Generic;
    
    public partial class diagnosticCenterHealthCheckUpPlan
    {
        public string dia_id { get; set; }
        public decimal plan_id { get; set; }
        public string planname { get; set; }
        public string cost { get; set; }
        public string others { get; set; }
    }
}
