//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Healthcare_sql
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiseaseToDepartment1
    {
        public string Department_name { get; set; }
        public string Disease_name { get; set; }
        public string Hindi_Name { get; set; }
        public int id { get; set; }
    }
}
