//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Healthcare_sql
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiseaseToDepartment
    {
        public string Department_name { get; set; }
        public string Body_system { get; set; }
        public string Organ { get; set; }
        public string Disease_name { get; set; }
        public string Hindi_Name { get; set; }
        public Nullable<double> id { get; set; }
        public string Diseasetreatment { get; set; }
        public string AbtDisease { get; set; }
        public string TrmtCntr { get; set; }
        public string vcAppendEmail { get; set; }
        public string vcAdditionalMsg { get; set; }
        public System.DateTime dtmsgUpdate { get; set; }
        public System.DateTime dtEmaildate { get; set; }
        public byte[] AboutDisease { get; set; }
        public byte[] TreatmentMethod { get; set; }
        public byte[] TreatementCenters { get; set; }
        public string Deptt1 { get; set; }
        public string Deptt2 { get; set; }
        public string Deptt3 { get; set; }
        public string Proc1 { get; set; }
        public string Proc2 { get; set; }
        public string Proc3 { get; set; }
        public string Proc4 { get; set; }
        public string Proc5 { get; set; }
        public string Proc6 { get; set; }
        public bool Chat { get; set; }
    }
}
