//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Healthcare_sql
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoctorsVisit
    {
        public string user_id { get; set; }
        public System.DateTime visit_date { get; set; }
        public string doctor_name { get; set; }
        public string vcDiseaseId { get; set; }
        public string city_name { get; set; }
        public string address { get; set; }
        public Nullable<decimal> pincode { get; set; }
        public string contact_no { get; set; }
        public string problem_condition_suspected { get; set; }
        public Nullable<double> visit_charges { get; set; }
        public string treatment_details { get; set; }
        public Nullable<decimal> doctor_rating { get; set; }
        public string vcOtherDiseaseName { get; set; }
        public string vcOtherDocName { get; set; }
        public string vcOtherCity { get; set; }
    }
}
