//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Healthcare_sql
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoctorsDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DoctorsDetail()
        {
            this.DoctorCategories = new HashSet<DoctorCategory>();
            this.DoctorsClinicTimings = new HashSet<DoctorsClinicTiming>();
            this.DoctorSkills = new HashSet<DoctorSkill>();
            this.DoctorsVisitingDetails = new HashSet<DoctorsVisitingDetail>();
        }
    
        public string doc_id { get; set; }
        public string first_name { get; set; }
        public string middle_name { get; set; }
        public string last_name { get; set; }
        public Nullable<System.DateTime> date_of_birth { get; set; }
        public string address { get; set; }
        public string city { get; set; }
        public string Zone { get; set; }
        public Nullable<decimal> pincode { get; set; }
        public string primary_std { get; set; }
        public string primary_phone { get; set; }
        public string secondry_std { get; set; }
        public string secondry_phone { get; set; }
        public string web_url { get; set; }
        public string email { get; set; }
        public string Qualification1 { get; set; }
        public string specialization_name1 { get; set; }
        public Nullable<decimal> year1 { get; set; }
        public string institute1 { get; set; }
        public string city1 { get; set; }
        public string qualification2 { get; set; }
        public string specialization_name2 { get; set; }
        public Nullable<decimal> year2 { get; set; }
        public string institute2 { get; set; }
        public string city2 { get; set; }
        public string Qualification3 { get; set; }
        public string specialization_name3 { get; set; }
        public Nullable<decimal> year3 { get; set; }
        public string institute3 { get; set; }
        public string city3 { get; set; }
        public string qualification4 { get; set; }
        public string specialization_name4 { get; set; }
        public Nullable<decimal> year4 { get; set; }
        public string institute4 { get; set; }
        public string city4 { get; set; }
        public string Registration_No { get; set; }
        public Nullable<decimal> Consultation_Fee { get; set; }
        public string experience1 { get; set; }
        public string no_of_years1 { get; set; }
        public string experience2 { get; set; }
        public Nullable<decimal> no_of_years2 { get; set; }
        public string experience3 { get; set; }
        public Nullable<decimal> no_of_years3 { get; set; }
        public string special_achievements { get; set; }
        public string memberships { get; set; }
        public string updated_by { get; set; }
        public Nullable<System.DateTime> updated_DateTime { get; set; }
        public string any_other { get; set; }
        public string designation { get; set; }
        public Nullable<decimal> category_code { get; set; }
        public string folder_name { get; set; }
        public string Approval { get; set; }
        public string vcPersonImageType { get; set; }
        public string vcImageName { get; set; }
        public byte[] imgPersonImage { get; set; }
        public string id { get; set; }
        public string vcUserName { get; set; }
        public string vcRoleType { get; set; }
        public string vcOthercity { get; set; }
        public string vcCountry { get; set; }
        public string vcimage { get; set; }
        public Nullable<int> IsMemberShipIdRequire { get; set; }
        public string hospital_id { get; set; }
        public bool isreferdoc { get; set; }
        public string Gender { get; set; }
        public string Source { get; set; }
        public Nullable<int> Visibility { get; set; }
        public Nullable<bool> NDA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DoctorCategory> DoctorCategories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DoctorsClinicTiming> DoctorsClinicTimings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DoctorSkill> DoctorSkills { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DoctorsVisitingDetail> DoctorsVisitingDetails { get; set; }
        public virtual DoctorWorkDetail DoctorWorkDetail { get; set; }
    }
}
