//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Healthcare_sql
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emp_offer
    {
        public int Emp_id { get; set; }
        public string Employee_id { get; set; }
        public string Emp_mail { get; set; }
        public string User_name { get; set; }
        public string mob { get; set; }
    }
}
