//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Healthcare_sql
{
    using System;
    using System.Collections.Generic;
    
    public partial class FellowPatientQuery
    {
        public string vcPatientId { get; set; }
        public string vcParentId { get; set; }
        public bool btIsAccept { get; set; }
        public bool btIsBlock { get; set; }
        public Nullable<int> intPostId { get; set; }
        public string vcUserName { get; set; }
        public string vcTouser { get; set; }
        public string vcQuery { get; set; }
    }
}
