//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Healthcare_sql
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupMember
    {
        public int GroupMemberPK_Id { get; set; }
        public int GroupPK_Id { get; set; }
        public string GroupMemberID { get; set; }
        public byte MType { get; set; }
        public bool Status { get; set; }
        public string Role { get; set; }
    
        public virtual Group Group { get; set; }
        public virtual ReferralEntityMaster ReferralEntityMaster { get; set; }
    }
}
