//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Healthcare_sql
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupMessageTransaction
    {
        public int GroupTransactionPk_Id { get; set; }
        public int GroupMessagePk_Id { get; set; }
        public string GroupMemberFrom { get; set; }
        public string GroupMemberTo { get; set; }
        public System.DateTime InsertedOn { get; set; }
        public short SeenStatus { get; set; }
        public byte GroupMemberFromType { get; set; }
        public byte GroupMemberToType { get; set; }
    
        public virtual GroupMessage GroupMessage { get; set; }
        public virtual ReferralEntityMaster ReferralEntityMaster { get; set; }
        public virtual ReferralEntityMaster ReferralEntityMaster1 { get; set; }
        public virtual ReferralStatusMaster ReferralStatusMaster { get; set; }
    }
}
