//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Healthcare_sql
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupMessage
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GroupMessage()
        {
            this.GroupMessageTransactions = new HashSet<GroupMessageTransaction>();
        }
    
        public int GroupMessagePk_Id { get; set; }
        public int GroupPK_Id { get; set; }
        public string GroupMemberID { get; set; }
        public string Message { get; set; }
        public System.DateTime InsertedOn { get; set; }
        public string AttachmentUrl { get; set; }
    
        public virtual Group Group { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GroupMessageTransaction> GroupMessageTransactions { get; set; }
    }
}
