//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Healthcare_sql
{
    using System;
    using System.Collections.Generic;
    
    public partial class healthnewscontent
    {
        public int id { get; set; }
        public string metatitle { get; set; }
        public string metadescriptions { get; set; }
        public string metakeywords { get; set; }
        public string healthnewscontent1 { get; set; }
        public string diseaseLinkid { get; set; }
        public string procedureLinkid { get; set; }
        public string hospitallinkid { get; set; }
        public string doctorLinkid { get; set; }
        public string image { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    }
}
