//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Healthcare_sql
{
    using System;
    using System.Collections.Generic;
    
    public partial class healthexchange
    {
        public string PatientFirstName { get; set; }
        public string PatientLastName { get; set; }
        public string PatientGender { get; set; }
        public string PatientMobile { get; set; }
        public string PatientEmail { get; set; }
        public string PatientAge { get; set; }
        public string PatientCountry { get; set; }
        public string PatientCity { get; set; }
        public string PatientBloodGroup { get; set; }
        public string PatientTransplantType { get; set; }
        public string DonorFirstName { get; set; }
        public string DonorLastName { get; set; }
        public string DonorGender { get; set; }
        public string DonorAge { get; set; }
        public string DonorBloodGroup { get; set; }
        public string PostQuery { get; set; }
        public string RelationwithPatient { get; set; }
        public int S_id { get; set; }
        public string querypostedby { get; set; }
        public string OtherFname { get; set; }
        public string OtherLname { get; set; }
        public string OtherRelawithPat { get; set; }
        public Nullable<System.DateTime> insertedon { get; set; }
        public bool Approval { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> folloupdate { get; set; }
        public string Updatedby { get; set; }
        public bool Isdisable { get; set; }
    }
}
