//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Healthcare_sql
{
    using System;
    using System.Collections.Generic;
    
    public partial class HospitalContactPersonDetail
    {
        public decimal Contact_ID { get; set; }
        public string Hos_ID { get; set; }
        public string Person_Name { get; set; }
        public string Designation { get; set; }
        public string Contact_No { get; set; }
        public string Email { get; set; }
        public string Other_Info { get; set; }
        public string Updated_by { get; set; }
        public Nullable<System.DateTime> Updated_Datetime { get; set; }
    
        public virtual HospitalsDetail HospitalsDetail { get; set; }
    }
}
