//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Healthcare_sql
{
    using System;
    using System.Collections.Generic;
    
    public partial class HospitalOffer
    {
        public string hos_id { get; set; }
        public string hos_name { get; set; }
        public string vchosdesc { get; set; }
        public string vcabthosp { get; set; }
        public string vcimage { get; set; }
        public string vclogo { get; set; }
        public string vcgroup { get; set; }
        public string vcdiscntdet { get; set; }
        public string vcweburl { get; set; }
        public string vcofferlogo { get; set; }
        public Nullable<int> Id { get; set; }
    }
}
