//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Healthcare_sql
{
    using System;
    using System.Collections.Generic;
    
    public partial class HospitalsDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HospitalsDetail()
        {
            this.HospitalConsultants = new HashSet<HospitalConsultant>();
            this.HospitalContactPersonDetails = new HashSet<HospitalContactPersonDetail>();
            this.HospitalDiagnostics = new HashSet<HospitalDiagnostic>();
            this.HospitalIndoorServices = new HashSet<HospitalIndoorService>();
            this.HospitalsPackageDetails = new HashSet<HospitalsPackageDetail>();
            this.HospitalVisitingConsultants = new HashSet<HospitalVisitingConsultant>();
            this.OpdTimings = new HashSet<OpdTiming>();
        }
    
        public string hos_id { get; set; }
        public string hospital_name { get; set; }
        public string hospital_category { get; set; }
        public string hospital_type { get; set; }
        public bool Allopathic { get; set; }
        public bool Aurvadic { get; set; }
        public bool Homeopathic { get; set; }
        public Nullable<bool> Unani { get; set; }
        public string owner_name { get; set; }
        public string address { get; set; }
        public string area_Zone { get; set; }
        public string city { get; set; }
        public Nullable<decimal> pincode { get; set; }
        public string primary_std { get; set; }
        public string primary_phone { get; set; }
        public string secondry_std { get; set; }
        public string secondry_phone { get; set; }
        public string fax_no { get; set; }
        public string email { get; set; }
        public string web_url { get; set; }
        public bool emergency_services { get; set; }
        public string emergency_std { get; set; }
        public string emergency_phone { get; set; }
        public bool ambulance_services { get; set; }
        public string ambulance_std { get; set; }
        public string ambulance_phone { get; set; }
        public Nullable<decimal> no_of_beds { get; set; }
        public string accredited_by { get; set; }
        public bool authorized_medico_legal_cases { get; set; }
        public Nullable<bool> health_insurance_tiesup { get; set; }
        public string other_info { get; set; }
        public string updated_by { get; set; }
        public Nullable<System.DateTime> updated_datetime { get; set; }
        public string super_speciality { get; set; }
        public string other_superSpeciality { get; set; }
        public Nullable<bool> others { get; set; }
        public bool icu_facility { get; set; }
        public string opd_timing { get; set; }
        public Nullable<decimal> category_code { get; set; }
        public string folder_name { get; set; }
        public Nullable<int> Count_hosId { get; set; }
        public string approval { get; set; }
        public string Ind_Name { get; set; }
        public string Ind_Mobile { get; set; }
        public string Ind_Email { get; set; }
        public string vcUserName { get; set; }
        public string vcRoleType { get; set; }
        public string vcAltEmail { get; set; }
        public string IntEmailId { get; set; }
        public string NatEmailId { get; set; }
        public string vcParentType { get; set; }
        public string vcChildHos { get; set; }
        public string Country { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HospitalConsultant> HospitalConsultants { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HospitalContactPersonDetail> HospitalContactPersonDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HospitalDiagnostic> HospitalDiagnostics { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HospitalIndoorService> HospitalIndoorServices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HospitalsPackageDetail> HospitalsPackageDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HospitalVisitingConsultant> HospitalVisitingConsultants { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OpdTiming> OpdTimings { get; set; }
    }
}
