//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Healthcare_sql
{
    using System;
    using System.Collections.Generic;
    
    public partial class HospitalIndoorService
    {
        public string hos_id { get; set; }
        public string ward_type { get; set; }
        public Nullable<decimal> no_of_beds { get; set; }
        public string charge { get; set; }
        public string updated_by { get; set; }
        public Nullable<System.DateTime> updated_datetime { get; set; }
    
        public virtual HospitalsDetail HospitalsDetail { get; set; }
    }
}
