//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Healthcare_sql
{
    using System;
    using System.Collections.Generic;
    
    public partial class HospitalVisitingConsultant
    {
        public string hos_id { get; set; }
        public string first_name { get; set; }
        public string middle_name { get; set; }
        public string last_name { get; set; }
        public Nullable<decimal> specialization_id { get; set; }
        public string specialization_name { get; set; }
        public string skill_expertize { get; set; }
        public string coming_from { get; set; }
        public string city { get; set; }
        public string day_time { get; set; }
        public string Qualification { get; set; }
        public Nullable<decimal> yEAR_Of_Exp { get; set; }
        public string updated_by { get; set; }
        public Nullable<System.DateTime> updated_datetime { get; set; }
        public string other_info { get; set; }
        public int VHd_id { get; set; }
        public string vcEmail { get; set; }
    
        public virtual HospitalsDetail HospitalsDetail { get; set; }
    }
}
