//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Healthcare_sql
{
    using System;
    using System.Collections.Generic;
    
    public partial class HospitalConsultant
    {
        public string hos_id { get; set; }
        public string first_name { get; set; }
        public string middle_name { get; set; }
        public string last_name { get; set; }
        public Nullable<decimal> specialization_id { get; set; }
        public string specialization_name { get; set; }
        public string skill_expertize { get; set; }
        public string day_Time { get; set; }
        public string city { get; set; }
        public string qualification { get; set; }
        public Nullable<decimal> year_of_exp { get; set; }
        public string updated_by { get; set; }
        public Nullable<System.DateTime> updated_datetime { get; set; }
        public string other_info { get; set; }
        public int Hd_id { get; set; }
        public string doc_id { get; set; }
        public string vcEmail { get; set; }
        public string clinic_area { get; set; }
        public Nullable<int> IsMemberShipIdRequire { get; set; }
        public Nullable<int> Iscard { get; set; }
        public string Experience { get; set; }
        public string image { get; set; }
        public bool videocons { get; set; }
        public string descp { get; set; }
        public bool Docdisp { get; set; }
        public string Indivdocid { get; set; }
    
        public virtual HospitalsDetail HospitalsDetail { get; set; }
    }
}
