//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Healthcare_sql
{
    using System;
    using System.Collections.Generic;
    
    public partial class HospitalDiagnostic
    {
        public string hos_id { get; set; }
        public string Service_Name { get; set; }
        public string SubService_Name { get; set; }
        public string remarks { get; set; }
        public string updated_by { get; set; }
        public Nullable<System.DateTime> updated_datetime { get; set; }
        public string rate { get; set; }
        public string test_name { get; set; }
        public string rate1 { get; set; }
        public string VC_OtherSub_ { get; set; }
        public decimal Service_id { get; set; }
    
        public virtual HospitalsDetail HospitalsDetail { get; set; }
    }
}
