//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Healthcare_sql
{
    using System;
    using System.Collections.Generic;
    
    public partial class Immunization
    {
        public string User_ID { get; set; }
        public string immunization_name { get; set; }
        public System.DateTime date { get; set; }
        public string immunization_other { get; set; }
        public Nullable<System.DateTime> date1 { get; set; }
        public string remarks { get; set; }
        public Nullable<System.DateTime> date2 { get; set; }
        public Nullable<System.DateTime> date3 { get; set; }
    }
}
