//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Healthcare_sql
{
    using System;
    using System.Collections.Generic;
    
    public partial class InsurancePlan
    {
        public string User_Id { get; set; }
        public string Provider_Name { get; set; }
        public string Plan_Policy_No { get; set; }
        public string Provider_Type { get; set; }
        public string Plan_Name { get; set; }
        public Nullable<System.DateTime> Date_Policy_Started { get; set; }
        public Nullable<System.DateTime> Date_Policy_Ended { get; set; }
        public string Employment_Linked_Plan { get; set; }
        public string Insured_Name { get; set; }
        public string Relationship_With_Insured { get; set; }
        public string Insured_Amount { get; set; }
        public string Yearly_Plan_Premium { get; set; }
        public string Contact_Person { get; set; }
        public string Contact_No { get; set; }
        public Nullable<int> Insurance_id { get; set; }
    }
}
