//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Healthcare_sql
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medication
    {
        public string vcDrugID { get; set; }
        public string User_ID { get; set; }
        public string vcDiseaseId { get; set; }
        public string Problem { get; set; }
        public string Form { get; set; }
        public string Quantity { get; set; }
        public string How_Often { get; set; }
        public string Status { get; set; }
        public string Other { get; set; }
        public string vcOtherDiseaseName { get; set; }
        public System.DateTime dtStartDate { get; set; }
        public string vcOtherDrugName { get; set; }
        public Nullable<System.DateTime> dtEndDate { get; set; }
        public Nullable<bool> hasRemoved { get; set; }
    }
}
