//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Healthcare_sql
{
    using System;
    using System.Collections.Generic;
    
    public partial class MIS_Table
    {
        public long ID { get; set; }
        public string Specialization_Name { get; set; }
        public string hos_Name { get; set; }
        public string doc_Name { get; set; }
        public string Skill_Name { get; set; }
        public string Disease_Name { get; set; }
        public string ServiceType { get; set; }
        public string city_Name { get; set; }
        public string Cost { get; set; }
        public string Doct_ID { get; set; }
        public string Hosp_ID { get; set; }
        public string Comment { get; set; }
        public string DocUrl { get; set; }
    }
}
