//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Healthcare_sql
{
    using System;
    using System.Collections.Generic;
    
    public partial class paid_specialist
    {
        public string doc_id { get; set; }
        public string Doc_name { get; set; }
        public string Qualification { get; set; }
        public string Specilization { get; set; }
        public string Yog { get; set; }
        public string Affiliations { get; set; }
        public string Apa { get; set; }
        public string Expertise { get; set; }
        public string CurrentClinic { get; set; }
        public string Front_heading1 { get; set; }
        public string Front_heading2 { get; set; }
        public string vcPersonImageType { get; set; }
        public string vcImageName { get; set; }
        public byte[] imgPersonImage { get; set; }
        public Nullable<int> doc_count { get; set; }
    }
}
