//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Healthcare_sql
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartnerSiteDetail
    {
        public decimal Site_ID { get; set; }
        public string Partner_Type_Name { get; set; }
        public string City_Name { get; set; }
        public string Locality { get; set; }
        public string Site_Name { get; set; }
        public string Address { get; set; }
        public Nullable<decimal> Pincode { get; set; }
        public string Discount { get; set; }
        public string Phone_No { get; set; }
        public string Mobile_No { get; set; }
        public string Updated_By { get; set; }
        public Nullable<System.DateTime> Updated_Datetime { get; set; }
    }
}
