//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Healthcare_sql
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient_Speak
    {
        public int Patient_ID { get; set; }
        public string Patient_Name { get; set; }
        public string Patient_City { get; set; }
        public string Speak_Title { get; set; }
        public string Description { get; set; }
    }
}
