//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Healthcare_sql
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientDisease
    {
        public int PatientDiseasePK_Id { get; set; }
        public string PatientId { get; set; }
        public int DiseaseId { get; set; }
        public int ReferralId { get; set; }
        public System.DateTime Insertedon { get; set; }
    
        public virtual DiseaseMaster DiseaseMaster { get; set; }
        public virtual ProviderReferral ProviderReferral { get; set; }
    }
}
