//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Healthcare_sql
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patinsudetail
    {
        public int Id { get; set; }
        public string vcqueryid { get; set; }
        public string Fname { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string Email { get; set; }
        public string mobile { get; set; }
        public string gender { get; set; }
        public string state { get; set; }
        public string city { get; set; }
        public string Insutype { get; set; }
        public string Memberscovered { get; set; }
        public Nullable<System.DateTime> InsertedOn { get; set; }
    }
}
