//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Healthcare_sql
{
    using System;
    using System.Collections.Generic;
    
    public partial class PDiscount
    {
        public int INDis_ID { get; set; }
        public string VCBIN { get; set; }
        public string VCCard_Type { get; set; }
        public string VCBank_Name { get; set; }
        public Nullable<decimal> NDiscountAmount { get; set; }
    }
}
