//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Healthcare_sql
{
    using System;
    using System.Collections.Generic;
    
    public partial class PGFamialy
    {
        public string Order_id { get; set; }
        public string bill_cus_Name1 { get; set; }
        public string bill_cus_Name2 { get; set; }
        public string bill_cus_Name3 { get; set; }
        public string bill_cus_Name4 { get; set; }
        public string bill_cus_Gender1 { get; set; }
        public string bill_cus_Gender2 { get; set; }
        public string bill_cus_Gender3 { get; set; }
        public string bill_cus_Gender4 { get; set; }
        public string bill_cus_age1 { get; set; }
        public string bill_cus_age2 { get; set; }
        public string bill_cus_age3 { get; set; }
        public string bill_cus_age4 { get; set; }
        public string bill_cus_Allergies1 { get; set; }
        public string bill_cus_Allergies2 { get; set; }
        public string bill_cus_Allergies3 { get; set; }
        public string bill_cus_Allergies4 { get; set; }
        public string bill_cus_blood1 { get; set; }
        public string bill_cus_blood2 { get; set; }
        public string bill_cus_blood3 { get; set; }
        public string bill_cus_blood4 { get; set; }
        public string bill_cus_phone1 { get; set; }
        public string bill_cus_phone2 { get; set; }
        public string bill_cus_phone3 { get; set; }
        public string bill_cus_phone4 { get; set; }
        public string bill_cus_email1 { get; set; }
        public string bill_cus_email2 { get; set; }
        public string bill_cus_email3 { get; set; }
        public string bill_cus_email4 { get; set; }
        public string bill_cus_address { get; set; }
        public string bill_cus_pincode { get; set; }
        public string bill_cus_city { get; set; }
        public string bill_cus_state { get; set; }
        public string bill_cus_country { get; set; }
        public string delivery_cust_name { get; set; }
        public string delivery_cust_address { get; set; }
        public string del_cus_pincode { get; set; }
        public string del_cus_city { get; set; }
        public string del_cus_state { get; set; }
        public string del_cus_country { get; set; }
        public string Amount { get; set; }
        public string bill_cus_Name { get; set; }
        public string Member_cardId1 { get; set; }
        public string Member_cardId2 { get; set; }
        public string Member_cardId3 { get; set; }
        public string Member_cardId4 { get; set; }
        public Nullable<int> Count_FMId { get; set; }
        public Nullable<System.DateTime> Order_date { get; set; }
        public Nullable<System.DateTime> End_date { get; set; }
        public string org_name { get; set; }
        public string approval { get; set; }
        public string bill_cus_mobile { get; set; }
    }
}
