//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Healthcare_sql
{
    using System;
    using System.Collections.Generic;
    
    public partial class PGIndividual
    {
        public string Order_id { get; set; }
        public string Merchant_id { get; set; }
        public string Name { get; set; }
        public string Contact_no { get; set; }
        public string Blood_Group { get; set; }
        public string Allergies { get; set; }
        public string Gender { get; set; }
        public string Marital_Status { get; set; }
        public string Age { get; set; }
        public string Amount { get; set; }
        public string Address { get; set; }
        public string Pincode { get; set; }
        public string Country { get; set; }
        public string State { get; set; }
        public string City { get; set; }
        public string Phone_No { get; set; }
        public string Email { get; set; }
        public string delivery_cust_name { get; set; }
        public string delivery_cust_address { get; set; }
        public string Delivery_pincode { get; set; }
        public string Delivery_country { get; set; }
        public string Delivery_state { get; set; }
        public string Delivery_city { get; set; }
        public string bill_cus_Name { get; set; }
        public Nullable<System.DateTime> Order_date { get; set; }
        public string Member_cardId { get; set; }
        public string caller_Std { get; set; }
        public string caller_Phone { get; set; }
        public string Emergency_Mobile { get; set; }
        public string caller_Email { get; set; }
        public string relation_type { get; set; }
        public string relationships { get; set; }
        public string Std { get; set; }
        public string Mobile { get; set; }
        public string other_Disease { get; set; }
        public string Other { get; set; }
        public string department_name { get; set; }
        public string Updated_by { get; set; }
        public Nullable<int> Count_MId { get; set; }
        public Nullable<System.DateTime> End_date { get; set; }
        public string org_name { get; set; }
        public string Disease_name { get; set; }
        public string approval { get; set; }
        public string caller_Mobile { get; set; }
        public string vcDeliveryEmail { get; set; }
        public string vcDeliveryPhone { get; set; }
        public string vcCompanyUrl { get; set; }
        public string vcCompanyName { get; set; }
        public string vcCompanyAddress { get; set; }
        public string vcCompanyCity { get; set; }
        public string vcCompanyState { get; set; }
        public string vcCompanyPin { get; set; }
        public string vcCompanyPhone { get; set; }
        public string vcCompanyEmail { get; set; }
        public string vcCompanyCountry { get; set; }
        public string vcContactPersonName { get; set; }
        public string vcContactPersonDesig { get; set; }
        public Nullable<int> Mem_type { get; set; }
        public string vcUsername { get; set; }
        public int Appt_flg { get; set; }
        public Nullable<System.DateTime> emaildate { get; set; }
        public string Code4disc { get; set; }
    }
}
