//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Healthcare_sql
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProviderReferral
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProviderReferral()
        {
            this.PatientDiseases = new HashSet<PatientDisease>();
            this.ReferralAppointment_api = new HashSet<ReferralAppointment_api>();
            this.ReferralTransactions_api = new HashSet<ReferralTransactions_api>();
        }
    
        public int ProviderReferralPK_Id { get; set; }
        public string ProviderFrom { get; set; }
        public string ProviderTo { get; set; }
        public string Patient { get; set; }
        public byte ProvFromType { get; set; }
        public byte ProvToType { get; set; }
        public byte PatientType { get; set; }
        public short Status { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public string QueryId { get; set; }
        public string Source { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatientDisease> PatientDiseases { get; set; }
        public virtual ReferralEntityMaster ReferralEntityMaster { get; set; }
        public virtual ReferralEntityMaster ReferralEntityMaster1 { get; set; }
        public virtual ProviderReferral ProviderReferrals1 { get; set; }
        public virtual ProviderReferral ProviderReferral1 { get; set; }
        public virtual ReferralEntityMaster ReferralEntityMaster2 { get; set; }
        public virtual ReferralStatusMaster ReferralStatusMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReferralAppointment_api> ReferralAppointment_api { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReferralTransactions_api> ReferralTransactions_api { get; set; }
    }
}
