//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Healthcare_sql
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProviderPatientDetail_api
    {
        public int id_pk { get; set; }
        public string providerid { get; set; }
        public string patientid { get; set; }
        public string mobile_no { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string address { get; set; }
        public string city { get; set; }
        public Nullable<decimal> pincode { get; set; }
        public string state { get; set; }
        public string country { get; set; }
        public string occupation { get; set; }
        public string vcOtherCity { get; set; }
        public string UserImage { get; set; }
        public string Age { get; set; }
        public string Gender { get; set; }
        public string Email { get; set; }
        public string Relation { get; set; }
        public Nullable<System.DateTime> InsertedOn { get; set; }
    }
}
