//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Healthcare_sql
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProviderPersonnel
    {
        public int ProviderpersonnelPK_Id { get; set; }
        public string EntityType { get; set; }
        public string UserName { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Name { get; set; }
        public System.DateTime InsertedOn { get; set; }
        public string vcimage { get; set; }
        public Nullable<int> btisapprove { get; set; }
        public string Designation { get; set; }
        public Nullable<int> Visibility { get; set; }
        public string Country { get; set; }
        public string City { get; set; }
        public Nullable<bool> NDA { get; set; }
    }
}
