//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Healthcare_sql
{
    using System;
    using System.Collections.Generic;
    
    public partial class QueryPatToComReply
    {
        public int intRepId { get; set; }
        public string vcComName { get; set; }
        public string vcPostMsg { get; set; }
        public string vcQueryId { get; set; }
        public bool btIsApprove { get; set; }
        public Nullable<System.DateTime> dtupdationdate { get; set; }
        public string vcPatientId { get; set; }
        public string vcPostType { get; set; }
        public Nullable<int> intIdToPost { get; set; }
        public string vcUserName { get; set; }
        public Nullable<System.DateTime> dtEmailTrigger { get; set; }
        public string vcAppendEmail { get; set; }
        public string vcAdditionalMsg { get; set; }
        public Nullable<System.DateTime> dtMsgUpdate { get; set; }
        public System.DateTime dtEmaildate { get; set; }
    }
}
