//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Healthcare_sql
{
    using System;
    using System.Collections.Generic;
    
    public partial class QueryPatToPatReply
    {
        public int intRepId { get; set; }
        public int intPostId { get; set; }
        public string vcPatientId { get; set; }
        public string vcToPatientId { get; set; }
        public string vcRepMsg { get; set; }
        public string vcRepType { get; set; }
        public string vcUserName { get; set; }
        public string vcToUser { get; set; }
        public string vcSenderName { get; set; }
        public Nullable<System.DateTime> dtCreationdate { get; set; }
        public string vcCreatedBy { get; set; }
        public Nullable<System.DateTime> vcupdationdate { get; set; }
        public string vcUpdatedBy { get; set; }
        public string vcStatus { get; set; }
        public System.DateTime dtLastActivity { get; set; }
    }
}
