//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Healthcare_sql
{
    using System;
    using System.Collections.Generic;
    
    public partial class RefAppTransactions_api
    {
        public int RefAppointTransactionPK_Id { get; set; }
        public int ReferralAppointmentPK_Id { get; set; }
        public string ProviderFromId { get; set; }
        public string ProviderToId { get; set; }
        public byte ProviderFromType { get; set; }
        public byte ProviderToType { get; set; }
        public short Status { get; set; }
        public string Comments { get; set; }
        public System.DateTime InsertedOn { get; set; }
        public Nullable<short> SeenStatus { get; set; }
        public Nullable<System.DateTime> AppointmentDate { get; set; }
        public string AppointmentTime { get; set; }
    
        public virtual ReferralAppointment_api ReferralAppointment_api { get; set; }
        public virtual ReferralEntityMaster ReferralEntityMaster { get; set; }
        public virtual ReferralEntityMaster ReferralEntityMaster1 { get; set; }
        public virtual ReferralStatusMaster ReferralStatusMaster { get; set; }
        public virtual ReferralStatusMaster ReferralStatusMaster1 { get; set; }
    }
}
