//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Healthcare_sql
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReferralStatusMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ReferralStatusMaster()
        {
            this.ConnectTransactions_api = new HashSet<ConnectTransactions_api>();
            this.ConnectTransactions_api1 = new HashSet<ConnectTransactions_api>();
            this.GroupConnections = new HashSet<GroupConnection>();
            this.GroupConnectionTransactions = new HashSet<GroupConnectionTransaction>();
            this.GroupConnectionTransactions1 = new HashSet<GroupConnectionTransaction>();
            this.GroupConnectionTransactions2 = new HashSet<GroupConnectionTransaction>();
            this.GroupMessageTransactions = new HashSet<GroupMessageTransaction>();
            this.ProviderReferrals = new HashSet<ProviderReferral>();
            this.RefAppTransactions_api = new HashSet<RefAppTransactions_api>();
            this.RefAppTransactions_api1 = new HashSet<RefAppTransactions_api>();
            this.ReferralAppointment_api = new HashSet<ReferralAppointment_api>();
            this.ReferralConnect_api = new HashSet<ReferralConnect_api>();
            this.ReferralConnect_api1 = new HashSet<ReferralConnect_api>();
            this.ReferralConnect_api2 = new HashSet<ReferralConnect_api>();
            this.ReferralTransactions_api = new HashSet<ReferralTransactions_api>();
            this.ReferralTransactions_api1 = new HashSet<ReferralTransactions_api>();
        }
    
        public short StatusID { get; set; }
        public string StatusDescription { get; set; }
        public string StatusByProvider { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConnectTransactions_api> ConnectTransactions_api { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConnectTransactions_api> ConnectTransactions_api1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GroupConnection> GroupConnections { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GroupConnectionTransaction> GroupConnectionTransactions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GroupConnectionTransaction> GroupConnectionTransactions1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GroupConnectionTransaction> GroupConnectionTransactions2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GroupMessageTransaction> GroupMessageTransactions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProviderReferral> ProviderReferrals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RefAppTransactions_api> RefAppTransactions_api { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RefAppTransactions_api> RefAppTransactions_api1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReferralAppointment_api> ReferralAppointment_api { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReferralConnect_api> ReferralConnect_api { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReferralConnect_api> ReferralConnect_api1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReferralConnect_api> ReferralConnect_api2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReferralTransactions_api> ReferralTransactions_api { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReferralTransactions_api> ReferralTransactions_api1 { get; set; }
    }
}
