//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Healthcare_sql
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReferralConnect_api
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ReferralConnect_api()
        {
            this.ConnectTransactions_api = new HashSet<ConnectTransactions_api>();
            this.ReferralRequestDetail_api = new HashSet<ReferralRequestDetail_api>();
        }
    
        public int ReferralConnectPK_Id { get; set; }
        public string Provider_Id { get; set; }
        public string Referral_Id { get; set; }
        public byte ProvType { get; set; }
        public byte RefrType { get; set; }
        public short ReferralStatusID { get; set; }
        public string RecordID { get; set; }
        public string AccessLevel { get; set; }
        public System.DateTime insertedon { get; set; }
        public short SeenStatus { get; set; }
        public Nullable<byte> ConnectRelation { get; set; }
    
        public virtual ConnectRelationMaster ConnectRelationMaster { get; set; }
        public virtual ConnectRelationMaster ConnectRelationMaster1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConnectTransactions_api> ConnectTransactions_api { get; set; }
        public virtual ReferralStatusMaster ReferralStatusMaster { get; set; }
        public virtual ReferralEntityMaster ReferralEntityMaster { get; set; }
        public virtual ReferralStatusMaster ReferralStatusMaster1 { get; set; }
        public virtual ReferralEntityMaster ReferralEntityMaster1 { get; set; }
        public virtual ReferralStatusMaster ReferralStatusMaster2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReferralRequestDetail_api> ReferralRequestDetail_api { get; set; }
    }
}
