//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Healthcare_sql
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReferralRequestDetail_api
    {
        public int ReferralRequestPK_Id { get; set; }
        public Nullable<int> ReferralConnectPK_Id { get; set; }
        public string FullName { get; set; }
        public string Email { get; set; }
        public string Mobile { get; set; }
        public Nullable<System.DateTime> InsertedOn { get; set; }
        public Nullable<byte> StatusID { get; set; }
    
        public virtual ReferralConnect_api ReferralConnect_api { get; set; }
    }
}
