//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Healthcare_sql
{
    using System;
    using System.Collections.Generic;
    
    public partial class review_doctor
    {
        public int Review_id { get; set; }
        public string Doc_id { get; set; }
        public string Review { get; set; }
        public string Reviews_name { get; set; }
        public string Reviews_Email { get; set; }
        public string Reviews_mob { get; set; }
        public Nullable<decimal> firstrating_value { get; set; }
        public Nullable<decimal> secondrating_value { get; set; }
        public Nullable<decimal> thirdrating_vlaue { get; set; }
        public Nullable<decimal> fourthrating_value { get; set; }
        public Nullable<decimal> fivthrating_value { get; set; }
        public Nullable<decimal> totalrating_value { get; set; }
        public Nullable<System.DateTime> date_review { get; set; }
        public string Approval { get; set; }
        public string first_name { get; set; }
        public string middle_name { get; set; }
        public string last_name { get; set; }
    }
}
