//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Healthcare_sql
{
    using System;
    using System.Collections.Generic;
    
    public partial class review_hospital
    {
        public string Hreview_id { get; set; }
        public string hos_id { get; set; }
        public string Review { get; set; }
        public string Reviews_name { get; set; }
        public string Reviews_mob { get; set; }
        public Nullable<System.DateTime> date_review { get; set; }
        public string Approval { get; set; }
        public string Reviews_Email { get; set; }
    }
}
