//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Healthcare_sql
{
    using System;
    using System.Collections.Generic;
    
    public partial class SearchProduct
    {
        public int ProductId { get; set; }
        public string ProductUrl { get; set; }
        public string ImageUrl { get; set; }
        public string DisplayName { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<int> BrandId { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public string CategoryName { get; set; }
        public string Brandname { get; set; }
    }
}
