//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Healthcare_sql
{
    using System;
    using System.Collections.Generic;
    
    public partial class SkillsMaster1
    {
        public decimal SKILL_ID { get; set; }
        public string SPECIALITY_NAME { get; set; }
        public string SKILL_NAME { get; set; }
        public string UPDATED_BY { get; set; }
        public Nullable<System.DateTime> UPDATED_DATETIME { get; set; }
        public string vcProcedureId { get; set; }
        public string VCPointId { get; set; }
        public Nullable<decimal> intPoints { get; set; }
        public Nullable<int> Id { get; set; }
    }
}
