//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Healthcare_sql
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpecialityClinicsCentreDetail
    {
        public decimal Centre_ID { get; set; }
        public string Hos_ID { get; set; }
        public string Centre_Name { get; set; }
        public string Address { get; set; }
        public string Std1 { get; set; }
        public Nullable<decimal> Phone1 { get; set; }
        public string Std2 { get; set; }
        public Nullable<decimal> Phone2 { get; set; }
        public string Email { get; set; }
        public string Web_Site { get; set; }
        public string Remarks { get; set; }
        public string Updated_By { get; set; }
        public Nullable<System.DateTime> Updated_DateTime { get; set; }
    }
}
