//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Healthcare_sql
{
    using System;
    using System.Collections.Generic;
    
    public partial class SuperSpecialityOPDTiming
    {
        public string hos_id { get; set; }
        public string SuperSpeciality_Name { get; set; }
        public string season { get; set; }
        public string Registration_Time { get; set; }
        public string Consultation_Time { get; set; }
        public string Day_Name { get; set; }
        public string Location { get; set; }
        public string Other { get; set; }
        public string Updated_by { get; set; }
        public Nullable<System.DateTime> Updated_DateTime { get; set; }
    }
}
