//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Healthcare_sql
{
    using System;
    using System.Collections.Generic;
    
    public partial class tabDoctorsVisitingDetail
    {
        public string doc_id { get; set; }
        public string hospital_name { get; set; }
        public string address { get; set; }
        public string city { get; set; }
        public string std_code { get; set; }
        public Nullable<decimal> phone_no { get; set; }
        public string day_time { get; set; }
        public string updated_by { get; set; }
        public Nullable<System.DateTime> updated_datetime { get; set; }
        public string others { get; set; }
        public string experience1 { get; set; }
        public int S_id { get; set; }
    }
}
