//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Healthcare_sql
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_providerlogindetail
    {
        public int ProvDetailPk_Id { get; set; }
        public string ProviderId { get; set; }
        public string ProviderType { get; set; }
        public string DeviceType { get; set; }
        public Nullable<System.DateTime> Insertedon { get; set; }
    }
}
