//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Healthcare_sql
{
    using System;
    using System.Collections.Generic;
    
    public partial class tempr
    {
        public string vcPatientId { get; set; }
        public string vcQueryId { get; set; }
        public string vcReplyId { get; set; }
        public string vcMemberName { get; set; }
        public string vcUserName { get; set; }
        public string vcReplyMessage { get; set; }
        public Nullable<bool> btIsApprove { get; set; }
        public string vcUpdatedBy { get; set; }
        public Nullable<System.DateTime> dtUpdationDate { get; set; }
        public string vcSenderId { get; set; }
        public string vcSenderName { get; set; }
        public string vcRepContact { get; set; }
        public string vcRepDesig { get; set; }
        public string vcRepliedBy { get; set; }
        public string vcSenderType { get; set; }
        public string vcSenderEmail { get; set; }
        public string vcShowRpl { get; set; }
    }
}
