//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Healthcare_sql
{
    using System;
    using System.Collections.Generic;
    
    public partial class tempp
    {
        public string vcPatientId { get; set; }
        public string vcQueryId { get; set; }
        public string vcMemberName { get; set; }
        public string vcPatientName { get; set; }
        public string vcPatientEmail { get; set; }
        public string vcPatientPhone { get; set; }
        public string vcPatientGender { get; set; }
        public string vcPatientAge { get; set; }
        public string vcDiseaseId { get; set; }
        public string vcDiseaseDepartment { get; set; }
        public string vcSufferingFrom { get; set; }
        public Nullable<bool> btIsPackage { get; set; }
        public string vcPackageName { get; set; }
        public Nullable<bool> btIsDiagnostic { get; set; }
        public string vcDiagnosticName { get; set; }
        public string vcQuerySubject { get; set; }
        public string txtQuery { get; set; }
        public Nullable<bool> btIsQueryApprove { get; set; }
        public string vcUpdatedBy { get; set; }
        public System.DateTime dtUpdationDate { get; set; }
        public string vcUserName { get; set; }
        public string vcRoleType { get; set; }
        public string vcOtherDisease { get; set; }
        public string vcOtherPackages { get; set; }
        public string vcOtherDiagnostics { get; set; }
        public string vcAppiontment { get; set; }
        public Nullable<bool> btIsWeek { get; set; }
        public Nullable<bool> btIsMonth { get; set; }
        public Nullable<bool> btIsMore { get; set; }
        public string vcPatientAddress { get; set; }
        public string vcPatientCity { get; set; }
        public string vcCountry { get; set; }
        public string vcTreatmentCity { get; set; }
        public string vcPreDisease { get; set; }
        public string vcOtherPreDisease { get; set; }
        public Nullable<bool> btIsAppiontment { get; set; }
        public Nullable<bool> btIsOther { get; set; }
        public string vcOtherType { get; set; }
        public Nullable<bool> btIsPaidQuery { get; set; }
        public string vcPatientOtherCity { get; set; }
        public string vcPatientType { get; set; }
        public string vccompany { get; set; }
    }
}
