//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Healthcare_sql
{
    using System;
    using System.Collections.Generic;
    
    public partial class tempq
    {
        public string vcPatientId { get; set; }
        public string vcDiseaseName { get; set; }
        public string vcQueryId { get; set; }
        public string vcReplyId { get; set; }
        public string vcMemberName { get; set; }
        public string vcTreatmentCity1 { get; set; }
        public string vcTreatmentCity2 { get; set; }
        public string vcTreatmentCity3 { get; set; }
        public string vcSubject { get; set; }
        public string vcQuery { get; set; }
        public Nullable<bool> btIsPackage { get; set; }
        public string vcPackageName { get; set; }
        public Nullable<bool> btIsDiagnostic { get; set; }
        public string vcDiagnosticName { get; set; }
        public Nullable<bool> btIsAppiontment { get; set; }
        public Nullable<bool> btIsOther { get; set; }
        public string vcOtherType { get; set; }
        public string vcUserName { get; set; }
        public string vcUpdatedBy { get; set; }
        public Nullable<System.DateTime> dtUpdationDate { get; set; }
        public string vcDuration { get; set; }
        public string vcPreDisease { get; set; }
        public string vcOtherPreDisease { get; set; }
        public string vcOtherDisease { get; set; }
        public string vcOtherPackages { get; set; }
        public string vcOtherDiagnostics { get; set; }
        public string vcOtherServices { get; set; }
        public string vcQueryStatus { get; set; }
        public Nullable<bool> btIsApprove { get; set; }
        public string vcPointId { get; set; }
        public string IsLead { get; set; }
        public string vcDocAppointment { get; set; }
        public Nullable<bool> btIsAssignDeptt { get; set; }
        public string vcAssignDeptt { get; set; }
        public string vcPaidProviderId { get; set; }
        public string vcpaystatus { get; set; }
        public string vcProviderId { get; set; }
        public string vcParentId { get; set; }
        public string vcInterestedField { get; set; }
        public string vcPatClinicalId { get; set; }
        public string vccompany { get; set; }
    }
}
