//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Healthcare_sql
{
    using System;
    using System.Collections.Generic;
    
    public partial class temphoscon
    {
        public string hos_id { get; set; }
        public string first_name { get; set; }
        public string middle_name { get; set; }
        public string last_name { get; set; }
        public string specialization_name { get; set; }
        public string skill_expertize { get; set; }
        public string day_Time { get; set; }
        public string city { get; set; }
        public string qualification { get; set; }
        public Nullable<decimal> year_of_exp { get; set; }
        public string updated_by { get; set; }
        public Nullable<System.DateTime> updated_datetime { get; set; }
        public string other_info { get; set; }
        public string doc_id { get; set; }
    }
}
