//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Healthcare_sql
{
    using System;
    using System.Collections.Generic;
    
    public partial class tquerypatienttreatmentcity
    {
        public string vcPatientId { get; set; }
        public string vcTreatmentCity1 { get; set; }
        public string vcQueryId { get; set; }
        public string vcTreatmentCity2 { get; set; }
        public string vcTreatmentCity3 { get; set; }
        public string vcUpdatedBy { get; set; }
        public Nullable<System.DateTime> dtUpdationDate { get; set; }
    }
}
