//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Healthcare_sql
{
    using System;
    using System.Collections.Generic;
    
    public partial class UploadMember_api
    {
        public int MemberIdPK { get; set; }
        public string ProviderId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string ProviderType { get; set; }
        public string HosName { get; set; }
        public string City { get; set; }
        public string HosID { get; set; }
        public string Image { get; set; }
        public string Designation { get; set; }
        public Nullable<bool> Success { get; set; }
        public string Comment { get; set; }
        public Nullable<System.DateTime> InsertedOn { get; set; }
        public string ParentID { get; set; }
    }
}
