//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Healthcare_sql
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_QueryPackage
    {
        public string vcPatientId { get; set; }
        public string vcSubject { get; set; }
        public string vcQueryId { get; set; }
        public string vcPatientGender { get; set; }
        public string vcPatientAge { get; set; }
        public string vcPatientCity { get; set; }
        public Nullable<System.DateTime> dtUpdationDate { get; set; }
        public string vcQuery { get; set; }
        public string vcPackageName { get; set; }
        public string vcAssignDeptt { get; set; }
    }
}
