//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Healthcare_sql
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewDoctorsdetail
    {
        public string doc_id { get; set; }
        public string first_name { get; set; }
        public string Middle_name { get; set; }
        public string last_name { get; set; }
        public string clinic_Address { get; set; }
        public string clinic_City { get; set; }
        public string address { get; set; }
        public string city { get; set; }
        public Nullable<decimal> category_code { get; set; }
        public string email { get; set; }
        public string category_name { get; set; }
        public string Approval { get; set; }
    }
}
